# use an existing docker image as a base
FROM node:16-alpine

WORKDIR /app
#download and install a dependency
COPY ./package.json ./
RUN npm install

COPY . .

#tell the image what to do when it starts
CMD ["npm","run","start"]