language:
  - generic
sudo: required
services:
  - docker

before_install:
  - docker build -t swadhinnayak/docker-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swadhinnayak/docker-test npm run test -- --coverage
after_success:
  - docker build -t swadhinnayak/multi-client ./client
  - docker build -t swadhinnayak/multi-nginx ./nginx
  - docker build -t swadhinnayak/multi-server ./server
  - docker build -t swadhinnayak/multi-worker ./worker
  #LOG in to docker  cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  #take those images and push them to docker hub
  - docker push swadhinnayak/multi-client
  - docker push swadhinnayak/multi-nginx
  - docker push swadhinnayak/multi-server
  - docker push swadhinnayak/multi-worker
